# .readthedocs.yaml

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2  # Use version 2 of the config file format

# Build configuration
build:
  os: ubuntu-22.04  # Use a recent Ubuntu image
  tools:
    python: "3.10"  # Specify the Python version for the build environment

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:  
        - docs  # Install your docs dependencies from requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Optionally, build in multiple formats
formats: all

# Requirements file path
requirements_file: docs/requirements.txt
